name: cleantemplate
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  logging: ^1.0.2
  package_info_plus: ^1.4.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
